### ISSUE TITLE
Server Offline w/V.07

### ISSUE THREAD

**Issue by DLCDavid** [olli-e/ISRT-Insurgency-Sandstorm-RCON-Query-Tool#11]
So, when I used the V0.7 and import my DB it always says "Server Offline".  When I use V0.6 it works, not offline.

**Comment by olli-e** [comment]
Hi David, let me know when you have time for a quick chat via steam or discord, then I can check directly with you. Or if you don‘t want that, please let me know if you used the installer or zip file and please give me the ip and queryport of the servers shown as offline. Does it happen everywhere or only in the server monitor or only in the main gui?

**Comment by olli-e** [comment]
You can find my contact data here: [https://www.isrt.info/?page_id=175](https://www.isrt.info/?page_id=175)

**Comment by olli-e** [comment]
oh and I forgot, are you on windows or what OS?

**Comment by DLCDavid** [comment]
Good day and thanks for getting back to me so quickly, we, the community 
really appreciate the RCON Tool since the last one we used was dropped 
from support and development.

I downloaded the "Zip" version from Github, launched the executable, and 
upon opening it asked me if I wanted to import the database.  I said yes 
and navigated to the old folder, V0.6's DB folder and it launched.  It 
states "Server Offline" in the lower message window with the faded 
picture background.  It does however display content after clicking on 
the "List Maps" button upper right area.

     I can be on Steam chat in about an hour or so, need to head out for 
a bit then will be home all day/evening,

DW.

------ Original Message ------

**Comment by DLCDavid** [comment]
Windows 10 Pro, Ver. 2004  I have my other machines updated to the 
latest but this is my main rig, gaming/business and wanted to wait a bit 
and have been to busy to get to it.

DW.

------ Original Message ------

**Comment by olli-e** [comment]
Thanks for letting me know. I had the same issue during development, but thought I had this sorted out. Could you pleaese let me know the ip and query port, so I can re-create this on my side (if you like, you can send it directly to me via madman@isrt.info). Which time zone are you located in? I‘m in CET so we are now in the new year celebration. Perhaps we can get together tomorrow and I‘m sure we will sort this out quickly. And of course I help my users as fast as possible ;-) In the meantime, I‘m trying to figure out, what the problem was as I ran across a similar problem.

Thanks,
Madman

**Comment by olli-e** [comment]
Closed, no tool problem, just a port problem on the server side.
